services:

   aboa_db:
      image: postgis/postgis:16-3.4
      container_name: aboa_db
      restart: always
      shm_size: 512M
      command: postgres -c max_connections=500 -c max_locks_per_transaction=500
      environment:
         - POSTGRES_DB=aboadb
         - POSTGRES_USER=aboa
         - POSTGRES_HOST_AUTH_METHOD=trust
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U aboa -d aboadb"]
         interval: 10s
         timeout: 5s
         retries: 5
      networks:
         - boa_network

   aboa:
      build:
         context: .
         dockerfile: Dockerfile.dev
      container_name: aboa
      restart: always
      hostname: aboa
      environment:
         - ABOA_DDBB_HOST=aboa_db
         - ABOA_RESOURCES_PATH=/aboa/src/config
         - ABOA_LOG_PATH=/log
         - ABOA_SCHEMAS_PATH=/aboa/src/schemas
         - ABOA_ARCHIVE_PATH=/aboa_archive
         - PYTHONDONTWRITEBYTECODE=1
      volumes:
         - .:/aboa:rw
      depends_on:
         aboa_db:
            condition: service_healthy
      shm_size: 512M
      networks:
         - boa_network

networks:
   boa_network:
      name: boa_network
